# .github/workflows/deploy-cloudfront.yml
name: Deploy to CloudFront

on:
  push:
    branches: [ "main" ]      # main 에 머지되면 배포
  workflow_dispatch:          # 수동 실행도 허용

env:
  AWS_REGION: ap-northeast-2              # 버킷·배포가 있는 리전
  S3_BUCKET: my-static-site-prod          # S3 버킷 이름
  CLOUDFRONT_DIST_ID: E2BI4WAO9XPJBF      # CloudFront 배포 ID
  BUILD_DIR: ${{ env.BUILD_DIR }}         # 로컬 빌드 산출물 폴더

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-22.04
    permissions:                         # OIDC 방식 IAM 롤을 위한 최소 권한
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # ────────────────────────
    # 1️.  애플리케이션 빌드
    # ────────────────────────
    - name: Set up Node (LTS)
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install & Build
      run: |
        npm ci
        npm run build           
    # ────────────────────────
    # 2️.  AWS 자격 증명 설정
    # ────────────────────────
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::056445322590:role/github-action-deploy
        aws-region: ${{ env.AWS_REGION }}

    # ────────────────────────
    # 3️. S3 동기화
    # ────────────────────────
    - name: Sync to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --delete --cache-control "public,max-age=31536000,immutable"
      env:
        SOURCE_DIR: ${{ env.BUILD_DIR }}
        AWS_S3_BUCKET: ${{ env.S3_BUCKET }}
        AWS_REGION:   ${{ env.AWS_REGION }}

    # ────────────────────────
    # 4️. CloudFront 무효화
    #    (HTML·json 같이 자주 바뀌는 파일만 지정)
    # ────────────────────────
    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id $CLOUDFRONT_DIST_ID \
          --paths "/*index.html" "/assets/*.json"
